### ISSUE TITLE
op_meaning in OBSERVATION_PERIODS for THL

### ISSUE THREAD

**Issue by DavideMessinaARS** [IMI-ConcePTION/DP3-MS-SLE#14]
Regarding the imputation of op_meaning in tables OBSERVATION_PERIODS for THL I need clarification.
Is the value that is being imputed **"observed_in_medicine_data"**? If not what are you using @visama?

**Comment by visama** [comment]
Yes, we can use this value. I make the changes next week using this value.

**Comment by DavideMessinaARS** [comment]
Can I close this issue? Did the script finish?

**Comment by visama** [comment]
I've made the changes in our data. Can I start running the script now? I can do it next week.

**Comment by DavideMessinaARS** [comment]
I've just released https://github.com/IMI-ConcePTION/DP3-MS-SLE/releases/tag/v1.0.3 which should add the subpopulation for THL

**Comment by visama** [comment]
No problem. Now there is a problem with the same script and function CreateSpells. Is the gap_allowed = days right or should it be gap_allowed = gap_days? days is at least for me a lubridate-function and not an integer. I debuged the function and the problem is line 109 where gap_allowed is added to date.

**Comment by DavideMessinaARS** [comment]
Again, sorry.

I've updated v1.0.4 with a few correction. Now it should run.

The issue is I can't really test the script because my simulated data don't have subpopulations.
I will probably add those data in the future for testing

**Comment by visama** [comment]
That's fine, no problem. I still get an error in the same script:

"Error in eval(ei, envir) : object 'subpopulations_non_empty' not found
Timing stopped at: 57.54 4.701 43.5"

**Comment by DavideMessinaARS** [comment]
@visama I've update the release with a few correction. Thanks for the patience

**Comment by visama** [comment]
I run the script 03_T3_40_compute_period_prevalence_MS.R and got the following 
error:

[1] "Version 1.0"
[1] "Check packages data.table and lubridate"
[1] "Assign date format to Start_study_time and End_study_time"
Error in as.character.POSIXt(as.POSIXlt(x), ...) : 
  'digits' must be numeric, integer valued

I think its about the function CountPrevalence and its line 17.

**Comment by DavideMessinaARS** [comment]
Inside the folder g_intermediate you should find the dataset D3_study_population_SAP1.
Can you check if the columns "cohort_entry_date" and "cohort_exit_date" inside of it are empty?

**Comment by visama** [comment]
This dataset has 4 date variables including those you mentioned. They have no missing values. It think that CountPrevalence-function line 17 is the problem:

Start_study_time<-as.IDate(as.character(Start_study_time,"%Y%m%d"),"%Y%m%d")
Error in as.character.POSIXt(as.POSIXlt(x), ...) : 
  'digits' must be numeric, integer valued

as.character(Start_study_time,"%Y%m%d")
Error in as.character.POSIXt(as.POSIXlt(x), ...) : 
  'digits' must be numeric, integer valued

**Comment by visama** [comment]
Start_study_time is a string "1996-01-01", which comes from recommended_start_date.

Dates in the dataset look fine in my eyes:
sapply(D3_study_population_SAP1, class)
                  person_id        entry_spell_category                  birth_date           cohort_entry_date            cohort_exit_date 
                "character"                      "Date"                      "Date"                      "Date"                      "Date" 
age_at_entry_spell_category        for_n_years_in_study 
                  "numeric"                   "numeric" 

Today Im available for a call before 12 CET and 13-15 CET.

**Comment by DavideMessinaARS** [comment]
I think I may have found the mistake. Do you have R 4.3.0 or a previous version?

**Comment by DavideMessinaARS** [comment]
I thought so. I've tried running the script on version 4.2.3 and it works while installing 4.3.0 and running the script failed.


In attachment a newer version of countprevalence to replace the existing one in p_macro ([CountPrevalence.zip](https://github.com/IMI-ConcePTION/DP3-MS-SLE/files/11496285/CountPrevalence.zip))

**Comment by visama** [comment]
Thanks, it works now. Next script gives me similar error message:

launch_step("p_steps/03_T3_41_compute_persontime_prevalence_MS.R")
[1] "MS"
Error in as.character.POSIXt(as.POSIXlt(x), ...) : 
  'digits' must be numeric, integer valued
Timing stopped at: 53.11 0.129 43.12

 I think the reason is the function CountPersonTime. Could you fix all the scripts with Start_study_time-variable used? Also 03_T3_42_compute_monthly_point_prevalence_MS.R gives the same error.

**Comment by visama** [comment]
Sorry, the script 03_T3_42_compute_monthly_point_prevalence_MS.R works fine.

**Comment by DavideMessinaARS** [comment]
Sorry, I didn't read your last few messages correctly and tough the issue was solved.

In the attachment a possible correction. Replace the current version of all the files with the one in [DP3-MS-SLE.zip](https://github.com/IMI-ConcePTION/DP3-MS-SLE/files/11705021/DP3-MS-SLE.zip)
Run the parameters and then from step 03_T3_41 onwards.

**Comment by visama** [comment]
Thanks, it now works without errors. I'll show results to Maarit on monday
